version: "3.3"

services:
  fastapi:
    container_name: fastapi_app  # Удобное имя контейнера
    build: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - /home/ubuntu/Conllu-FastApi/data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
